me.dir() => string src;
Machine.add( src + "orb_update.ck" ) => int oupd;
Machine.add( src + "stop_event.ck" ) => int stopper;
Machine.add( src + "orb.ck" ) => int orb;
Machine.add( src + "orb_sys.ck" ) => int orbsys;
Machine.add( src + "recorder.ck" ) => int recorder;
Machine.add( src + "sound.ck" ) => int sound;
Machine.add( src + "manager.ck" ) => int manager;
Machine.add( src + "session.ck" ) => int session;
